"""initial_schema

Revision ID: 08fc8d728449
Revises: 
Create Date: 2026-05-30 20:28:14.764458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))
from voiceagent.db.models import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = '08fc8d728449'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(length=255), nullable=True),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('tools_json', sa.Text(), nullable=True),
    sa.Column('sip_trunk_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('role', sa.Enum('admin', 'agent', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('automations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'phone', name='uq_contact_user_phone')
    )
    op.create_index('ix_contacts_user_id', 'contacts', ['user_id'], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=True),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='template_status'), nullable=False),
    sa.Column('wa_template_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_table('whatsapp_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('webhook_verify_token', sa.String(length=128), nullable=True),
    sa.Column('app_secret', sa.String(length=128), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('automation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('automation_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('steps_results', sa.JSON(), nullable=True),
    sa.Column('resume_at', UTCDateTime(), nullable=True),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'sending', 'completed', 'failed', name='broadcast_status'), nullable=False),
    sa.Column('scheduled_at', UTCDateTime(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_config_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='call_direction'), nullable=False),
    sa.Column('status', sa.Enum('dialing', 'active', 'completed', 'failed', name='call_status'), nullable=False),
    sa.Column('from_number', sa.String(length=50), nullable=True),
    sa.Column('to_number', sa.String(length=50), nullable=True),
    sa.Column('livekit_room_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', UTCDateTime(), nullable=True),
    sa.Column('ended_at', UTCDateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Float(), nullable=True),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['agent_config_id'], ['agent_configs.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_tags',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('open', 'pending', 'closed', name='conversation_status'), nullable=False),
    sa.Column('last_message_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_contact_id', 'conversations', ['contact_id'], unique=False)
    op.create_table('flow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('current_node_id', sa.String(length=128), nullable=True),
    sa.Column('state', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flow_runs_contact_flow', 'flow_runs', ['contact_id', 'flow_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcast_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('broadcast_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'read', 'failed', name='broadcast_recipient_status'), nullable=False),
    sa.Column('sent_at', UTCDateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('close_date', UTCDateTime(), nullable=True),
    sa.Column('status', sa.Enum('open', 'won', 'lost', name='deal_status'), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction'), nullable=False),
    sa.Column('type', sa.Enum('text', 'image', 'video', 'audio', 'document', 'location', 'template', 'interactive', 'note', name='message_type'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'read', 'failed', name='message_status'), nullable=False),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    op.create_table('transcript_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('started_at', UTCDateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_turns')
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_table('deals')
    op.drop_table('broadcast_recipients')
    op.drop_table('pipeline_stages')
    op.drop_index('ix_flow_runs_contact_flow', table_name='flow_runs')
    op.drop_table('flow_runs')
    op.drop_index('ix_conversations_contact_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('contact_tags')
    op.drop_table('calls')
    op.drop_table('broadcasts')
    op.drop_table('automation_logs')
    op.drop_table('whatsapp_configs')
    op.drop_table('tags')
    op.drop_table('pipelines')
    op.drop_table('message_templates')
    op.drop_table('flows')
    op.drop_index('ix_contacts_user_id', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('automations')
    op.drop_table('users')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###
